apiVersion: skaffold/v1
kind: Config

metadata:
  name: bind-dnssec-controller

build:
  artifacts:
    - image: farberg/bind-dnssec-config
      context: controller
    - image: farberg/bind-dnssec-runner
      context: bindrunner

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
