apiVersion: skaffold/v4beta11
kind: Config

metadata:
  name: bind-dnssec-controller

build:
  artifacts:
    - image: farberg/bind-dnssec-config
      context: controller
    - image: farberg/bind-dnssec-runner
      context: bindrunner

manifests:
  rawYaml:
    - k8s/*.yaml

deploy:
  kubectl: {}
