apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: dnsupdates.dnsseczone.farberg.de
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: dnsseczone.farberg.de

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: dnsupdates
    # singular name to be used as an alias on the CLI and for display
    singular: dnsupdate
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: DnsUpdate
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - du

  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dnsserver:
                  type: string
                keystring:
                  type: string
                records:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      ttl_seconds:
                        type: integer
                      record:
                        type: object
                        properties:
                          type:
                            type: string
                            enum: ["A", "AAAA", "CNAME", "NS", "PTR"]
                          contents:
                            type: string
                      service:
                        type: object
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                    oneOf:
                      - properties:
                        required: ["name", "ttl_seconds", "record"]
                      - properties:
                        required: ["name", "ttl_seconds", "service"]
            status:
              type: object
              properties:
                ready:
                  type: boolean

      # subresources describes the subresources for custom resources.
      subresources:
        # status enables the status subresource.
        status: {}
