apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bind-dnssec-config
spec:
  selector:
    matchLabels:
      app: bind_dnssec_config
  replicas: 1
  template:
    metadata:
      labels:
        app: bind_dnssec_config
    spec:
      containers:
        - name: configgen
          image: farberg/bind-dnssec-config
          args:
            - "--configdir"
            - "/etc/bind"
            - "--vardir"
            - "/var/bind/gen"
            - "--nameserver1"
            - "cloud-ns.cloud-ns.dhbw-mannheim.de"
            # - "--nameserver2"
            # - "cloud-ns.dhbw-mannheim.de"
            - "--bind-verbose-output"
            - "--log-level"
            - "trace"
            - "--dryrun"
            #- "--run-reconcilers"
            #- "zone"
            #- "--debug-create-crds"
            #- "10000"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/bind/
            - name: var-volume
              mountPath: /var/bind/gen
          ports:
            - containerPort: 7777
        #          livenessProbe:
        #            httpGet:
        #              path: /health/liveness
        #              port: 7777
        #            initialDelaySeconds: 5
        #            periodSeconds: 30
        #          readinessProbe:
        #            httpGet:
        #              path: /health/readiness
        #              port: 7777
        #            initialDelaySeconds: 5
        #            periodSeconds: 30
        #          resources:
        #            limits:
        #              cpu: ".1"
        #              memory: "256Mi"
        - name: bindrunner
          image: farberg/bind-dnssec-runner
          ports:
            - containerPort: 53
          volumeMounts:
            - name: config-volume
              mountPath: /etc/bind/
            - name: var-volume
              mountPath: /var/bind/gen
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: var-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: bind-dnssec-config-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dyn-ns.cloud.dhbw-mannheim.de
    metallb.universe.tf/allow-shared-ip: "edsc-tools"
spec:
  selector:
    app: bind_dnssec_config
  type: LoadBalancer
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
